project_id = "xiufgczyecwgnkbyroow"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.icp-wizard]
    verify_jwt = false
  [functions.persona-wizard]
    verify_jwt = false
  [functions.invite-user]
    verify_jwt = false
  [functions.manage-project-connection]
    verify_jwt = false
  [functions.campaign-wizard]
    verify_jwt = false
  [functions.create-notion-campaign-brief]
    verify_jwt = false
  [functions.brand-voice-wizard]
    verify_jwt = false
  [functions.generate-campaign-content]
    verify_jwt = false
  [functions.bulk-generate-campaign-content]
    verify_jwt = false
  [functions.push-asset-to-notion]
    verify_jwt = false
  [functions.bulk-push-campaign-to-notion]
    verify_jwt = false
