// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xiufgczyecwgnkbyroow.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhpdWZnY3p5ZWN3Z25rYnlyb293Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ3MDE0ODIsImV4cCI6MjA5MDI3NzQ4Mn0.5KpMPFMSLcCnjN6NDUrbSXBJTTFLL3TE-Yq-38zz-cs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});